"""empty message

Revision ID: a42832337064
Revises: 631598486e68
Create Date: 2025-05-20 20:02:35.183232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42832337064'
down_revision = '631598486e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.drop_column('type')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_preview', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('images_businessId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])
        batch_op.drop_column('businessId')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('reviews_businessId_fkey', type_='foreignkey')
        batch_op.drop_constraint('reviews_userId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('userId')
        batch_op.drop_column('businessId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('businessId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reviews_userId_fkey', 'users', ['userId'], ['id'])
        batch_op.create_foreign_key('reviews_businessId_fkey', 'businesses', ['businessId'], ['id'])
        batch_op.drop_column('business_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('businessId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('images_businessId_fkey', 'businesses', ['businessId'], ['id'])
        batch_op.drop_column('is_preview')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
